package io.github.jdawg867.anvildesk.runtime

import java.io.File
import java.io.FileOutputStream
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.StandardCopyOption

object ManagedGuestDns {
    private const val MAX_DNS_SERVERS = 4

    fun normalize(servers: List<String>): List<String> {
        val normalized = servers
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .map(::requireNumericIpLiteral)
            .distinct()
            .take(MAX_DNS_SERVERS)

        require(normalized.isNotEmpty()) { "Active Android network did not provide a usable DNS server" }
        return normalized
    }

    fun write(
        destination: File,
        servers: List<String>,
    ): File {
        val parent = destination.parentFile
            ?: throw IllegalArgumentException("Managed DNS file must have a parent directory")
        ensurePlainDirectory(parent)
        require(!Files.isSymbolicLink(destination.toPath())) {
            "Managed DNS destination must not be a symbolic link"
        }

        val normalized = normalize(servers)
        val temporary = File(parent, ".${destination.name}.part")
        require(!Files.isSymbolicLink(temporary.toPath())) {
            "Managed DNS temporary path must not be a symbolic link"
        }

        val content = buildString {
            append("# Generated by AnvilDesk from Android active-network DNS\n")
            normalized.forEach { append("nameserver ").append(it).append('\n') }
        }

        FileOutputStream(temporary).use { output ->
            output.write(content.toByteArray(Charsets.US_ASCII))
            output.fd.sync()
        }

        try {
            Files.move(
                temporary.toPath(),
                destination.toPath(),
                StandardCopyOption.REPLACE_EXISTING,
                StandardCopyOption.ATOMIC_MOVE,
            )
        } catch (error: AtomicMoveNotSupportedException) {
            temporary.delete()
            throw MutableRuntimeException("Atomic managed DNS write is not supported", error)
        }
        return destination
    }

    private fun requireNumericIpLiteral(value: String): String {
        require(!value.contains('%')) { "Scoped DNS addresses are not accepted" }
        return if (value.contains(':')) {
            require(value.length in 2..45) { "Invalid IPv6 DNS address length" }
            require(value.count { it == ':' } >= 2) { "Invalid IPv6 DNS address" }
            require(value.all { it in '0'..'9' || it in 'a'..'f' || it in 'A'..'F' || it == ':' || it == '.' }) {
                "DNS server must be a numeric IPv6 address"
            }
            value.lowercase()
        } else {
            val octets = value.split('.')
            require(octets.size == 4) { "DNS server must be a numeric IPv4 or IPv6 address" }
            require(octets.all { octet ->
                octet.isNotEmpty() && octet.length <= 3 && octet.all(Char::isDigit) &&
                    octet.toIntOrNull()?.let { it in 0..255 } == true
            }) { "Invalid IPv4 DNS address" }
            octets.joinToString(".") { it.toInt().toString() }
        }
    }

    private fun ensurePlainDirectory(directory: File) {
        val path = directory.toPath()
        if (Files.exists(path, LinkOption.NOFOLLOW_LINKS)) {
            require(!Files.isSymbolicLink(path)) { "Managed DNS directory must not be a symlink" }
            require(Files.isDirectory(path, LinkOption.NOFOLLOW_LINKS)) {
                "Managed DNS parent path is not a directory"
            }
        } else {
            require(directory.mkdirs()) { "Could not create managed DNS directory" }
        }
    }
}
